from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected exactly one match, got {count}")
    return text.replace(old, new, 1)


path = Path("Sources/UI/EmbyMediaDetailView.swift")
text = path.read_text()

text = replace_once(text,
'''                if let playableItem = model.primaryPlayableItem {\n                    Button { Task { await model.play(playableItem) } } label: {\n                        HStack(spacing: 9) {\n                            if model.isResolvingPlayback { ProgressView().tint(.white) }\n                            else { Image(systemName: "play.fill").font(.system(size: 15, weight: .bold)) }\n                            Text(model.primaryPlayButtonTitle).font(.headline)\n                        }\n                        .foregroundColor(.white)\n                        .frame(width: contentWidth, height: 50)\n                        .background(Color.blue)\n                        .clipShape(RoundedRectangle(cornerRadius: 17, style: .continuous))\n                    }\n                    .buttonStyle(DetailPressButtonStyle())\n                    .disabled(model.isResolvingPlayback)\n                }\n''',
'''                if let playableItem = model.primaryPlayableItem {\n                    Button { Task { await model.play(playableItem) } } label: { primaryPlayButtonLabel(width: contentWidth) }\n                        .buttonStyle(DetailPressButtonStyle())\n                        .disabled(model.isResolvingPlayback)\n                }\n''', "primary play button body")

text = replace_once(text,
'''    @ViewBuilder\n    private func heroIdentity(width: CGFloat) -> some View {\n''',
'''    private func primaryPlayButtonLabel(width: CGFloat) -> some View {\n        let progress = model.primaryPlayButtonProgress\n        let iconOffset = -min(82, max(54, width * 0.21))\n        return ZStack(alignment: .bottomLeading) {\n            RoundedRectangle(cornerRadius: 17, style: .continuous).fill(Color.blue)\n\n            if progress > 0 {\n                GeometryReader { proxy in\n                    ZStack(alignment: .leading) {\n                        Capsule().fill(Color.white.opacity(0.18))\n                        Capsule().fill(Color.white.opacity(0.84))\n                            .frame(width: proxy.size.width * CGFloat(min(max(0, progress), 1)))\n                    }\n                }\n                .frame(height: 3)\n                .padding(.horizontal, 13)\n                .padding(.bottom, 4)\n            }\n\n            ZStack {\n                if model.isResolvingPlayback { ProgressView().tint(.white).offset(x: iconOffset) }\n                else { Image(systemName: "play.fill").font(.system(size: 15, weight: .bold)).offset(x: iconOffset) }\n\n                if model.isResolvingPlayback {\n                    Text(model.primaryPlayButtonTitle).font(.headline)\n                } else if model.primaryPlayButtonShowsResume {\n                    VStack(spacing: 1) {\n                        Text("继续播放").font(.system(size: 18, weight: .bold))\n                        if let position = model.primaryPlayButtonPositionText {\n                            Text("上次播放到：\\(position)").font(.system(size: 11.5, weight: .medium)).opacity(0.90)\n                        }\n                    }\n                } else {\n                    Text(model.primaryPlayButtonTitle).font(.headline)\n                }\n            }\n            .foregroundColor(.white)\n            .frame(width: width, height: 50)\n        }\n        .frame(width: width, height: 50)\n        .clipShape(RoundedRectangle(cornerRadius: 17, style: .continuous))\n    }\n\n    @ViewBuilder\n    private func heroIdentity(width: CGFloat) -> some View {\n''', "resume-aware play button label")

text = replace_once(text,
'''                if mediaInfoExpanded {\n                    ScrollView(.horizontal, showsIndicators: false) {\n                        HStack(alignment: .top, spacing: 12) {\n                            ForEach(Array(model.mediaStreams.enumerated()), id: \\.offset) { index, stream in\n                                mediaStreamCard(stream, ordinal: index)\n                            }\n                        }\n                        .padding(.horizontal, 20)\n                    }\n                    .transition(.opacity.combined(with: .move(edge: .top)))\n                }\n''',
'''                VStack(spacing: 0) {\n                    if mediaInfoExpanded {\n                        ScrollView(.horizontal, showsIndicators: false) {\n                            HStack(alignment: .top, spacing: 12) {\n                                ForEach(Array(model.mediaStreams.enumerated()), id: \\.offset) { index, stream in\n                                    mediaStreamCard(stream, ordinal: index)\n                                }\n                            }\n                            .padding(.horizontal, 20)\n                        }\n                        .transition(.opacity.combined(with: .move(edge: .top)))\n                    }\n                }\n                .frame(maxWidth: .infinity, alignment: .leading)\n                .clipped()\n''', "clipped media info reveal")

text = replace_once(text,
'''    var primaryPlayButtonTitle: String {\n        if isResolvingPlayback { return "正在准备播放…" }\n        if isSeries, let episode = primaryPlayableItem {\n            let index = episode.indexNumber.map { "E\\($0)" } ?? ""\n            return episode.playbackProgress > 0.001 ? "继续播放 \\(index)" : "播放 \\(index)"\n        }\n        return item.playbackProgress > 0.001 ? "继续播放" : "播放"\n    }\n''',
'''    var primaryPlayButtonShowsResume: Bool {\n        guard !displayedPlayed, let playable = primaryPlayableItem else { return false }\n        return playable.playbackProgress > 0.001\n    }\n\n    var primaryPlayButtonProgress: Double {\n        guard primaryPlayButtonShowsResume, let playable = primaryPlayableItem else { return 0 }\n        return min(1, max(0, playable.playbackProgress))\n    }\n\n    var primaryPlayButtonPositionText: String? {\n        guard primaryPlayButtonShowsResume, let ticks = primaryPlayableItem?.userData?.playbackPositionTicks, ticks > 0 else { return nil }\n        let total = max(0, Int(Double(ticks) / AppIdentity.ticksPerSecond))\n        let hours = total / 3600\n        let minutes = (total % 3600) / 60\n        let seconds = total % 60\n        if hours > 0 { return String(format: "%d:%02d:%02d", hours, minutes, seconds) }\n        return String(format: "%02d:%02d", minutes, seconds)\n    }\n\n    var primaryPlayButtonTitle: String {\n        if isResolvingPlayback { return "正在准备播放…" }\n        return primaryPlayButtonShowsResume ? "继续播放" : "播放"\n    }\n''', "resume-aware primary play state")

path.write_text(text)
