from pathlib import Path

entries = {
    'docs/project/PROJECT_STATE.md': '''\n\n## Active: Search page / recommendations — Build247 / 0.14.80\n\nBuild246 / 0.14.79 is now target-device tested and rejected as final: Search keyboard focus still lifts the bottom Dock, the recommendation wall is still slow on entry/later posters, the required Movie/Series whitelist was not sufficiently enforced at the returned-item level, and recommendation load-more still causes visible container twitch.\n\nBuild247 exact CI product source `5f693d82041bbb59d3fe481aa708b22a5feda42d` changes the Search-owned path only. The visible Search Dock is mounted by `EmbyServerRootViewV3` instead of the nested Search `NavigationView`; returned recommendations are hard-filtered to actual Emby `Movie`/`Series` types; `RootView` starts one process-lifetime bounded 60-item recommendation warm after `SessionStore.restore()`; the warm reuses the existing `EmbyImageDiskCache` and `EmbyDecodedImageRenderPool` for the exact Search poster URLs; and the Search recommendation grid no longer performs incremental Suggestions requests or item-count growth while the user scrolls. Keyword Search remains separate because its term is unavailable at app launch. Shared `EmbyPosterGrid.swift` / `EmbySharedImageAndNavigation.swift` and all Player/Transport/playback-cache/PiP/Frozen contracts are unchanged.\n\nDedicated Xcode 16.4 Release run/job `33258792907 / 99117036605` succeeded; artifact `9716657082`; artifact digest `sha256:9628b0c608488edbfc5af477199e847e5a35b119d4ab96edbecd036cbde4bfd1`; IPA SHA-256 `952b2daeef4bc01fe62476611c6620cf7ce79d3905d87bd82336e4650d0d69b0`; source ZIP SHA-256 `44494de6213883b8bee16b6e99336b33073ed38b17a53062f9be7a2cff22b73d`; independently verified identity `com.embyplayerlab.app`, `0.14.80 (247)`, MinOS 15.0, IPA integrity passed. Evidence: **Code written ✅ / CI passed ✅ / IPA produced+independently verified ✅ / real-device tested ❌ / stable/frozen ❌**.\n''',
    'docs/project/BUILD_TEST_INDEX.md': '''\n\n### Build247 / 0.14.80 — Search startup recommendation warm candidate\n\n- Build246 target-device evidence: Dock still rises with keyboard; recommendation entry/later posters remain slow; returned-type whitelist must be explicit; recommendation load-more still twitches. Build246 is real-device tested and rejected as final.\n- exact CI product source: `5f693d82041bbb59d3fe481aa708b22a5feda42d`.\n- Search-only architecture: server-root owns the visible Search Dock; returned recommendation items are hard-filtered to `Movie`/`Series`; app startup restore begins one bounded 60-item recommendation/poster warm; Search consumes the same task; recommendation grid is fixed and performs no active-scroll load-more. Existing persistent image disk cache and decoded pool remain the cache authorities.\n- run/job: `33258792907 / 99117036605` — success.\n- artifact: `OnePlayer-0.14.80-Build247-Search`; ID `9716657082`; digest `sha256:9628b0c608488edbfc5af477199e847e5a35b119d4ab96edbecd036cbde4bfd1`.\n- IPA SHA-256: `952b2daeef4bc01fe62476611c6620cf7ce79d3905d87bd82336e4650d0d69b0`.\n- source ZIP SHA-256: `44494de6213883b8bee16b6e99336b33073ed38b17a53062f9be7a2cff22b73d`.\n- independent package verification: bundle `com.embyplayerlab.app`; OnePlayer `0.14.80 (247)`; `MinimumOSVersion=15.0`; IPA `unzip -t` passed.\n- evidence: **Code written ✅ / CI passed ✅ / IPA produced+verified ✅ / target-device pending / not stable.**\n''',
    'docs/project/TECHNICAL_DECISIONS.md': '''\n\n## Search recommendation startup warm and Dock ownership — Build247 candidate\n\n- The visible server Dock belongs to `EmbyServerRootViewV3`. Search may host keyboard-responsive navigation/content, but it must not own a second visible Dock inside that nested tree. This is the direct replacement for the Build244–246 safe-area-only attempts that still lifted Dock on device.\n- Search landing recommendations use a client-visible whitelist: actual returned `LibraryItem.type` must be `Movie` or `Series`. `IncludeItemTypes=Movie,Series` is a server-query optimization, not the final UI authority.\n- Because landing recommendations are independent of a typed keyword, saved-session recommendation metadata and exact poster URLs may be warmed once after app startup restore. The Search page consumes that shared in-flight/completed process-lifetime work. Typed keyword results are not precomputed.\n- Recommendation presentation uses a bounded fixed set for the current candidate; do not mutate the recommendation grid through incremental Suggestions requests while the user is scrolling. This isolates Search from the Build246 load-more twitch without changing the shared poster-grid owner.\n- Existing `EmbyImageDiskCache` remains the persistent poster-byte authority and `EmbyDecodedImageRenderPool` remains the decoded-memory authority. Do not add a Search-specific second disk image cache.\n- This decision is candidate-level until Build247 target-device testing; it does not mark Search stable/frozen.\n'''
}

for filename, block in entries.items():
    path = Path(filename)
    text = path.read_text()
    marker = block.strip().splitlines()[0]
    if marker not in text:
        if not text.endswith('\n'):
            text += '\n'
        text += block
        path.write_text(text)
