from pathlib import Path

module = Path('docs/project/MODULE_STATUS.md')
text = module.read_text()
old_start = '| Search page / recommendations |'
lines = text.splitlines()
for i, line in enumerate(lines):
    if line.startswith(old_start):
        lines[i] = '| Search page / recommendations | **Active — Build249 recommendation rejected; Build250 CI/IPA verified, target-device pending** | Build248 target-device evidence accepts the root-owned/safe-area-compensated Dock and keyboard behavior. Build249 / 0.14.82 target-device log `OnePlayer-App-1788020447.log` shows 21 views / 19 eligible and each of the first Movie/TV Suggestions calls returned 9 items but `accepted=0`; the second client whitelist rejected Suggestions items whose decoded `Type` is absent, forcing serial traversal. Build250 / 0.14.83 exact CI source `6e7ae960bd3cc353b8d6146aea363f3876e9e8e8` keeps CollectionType + server `IncludeItemTypes` Movie/Series filtering, requires actual Movie/Series when returned `Type` exists, and when `Type` is omitted accepts only results produced by an exclusively Movie/Series request. Run/job `33263279291 / 99128762968` passed; artifact `9717900754`; IPA SHA-256 `f213b3d6f30ac101d563e3894c3352fdcd9c9bcb46c7a266faa48c8577e73ada`; MinOS 15.0 verified. Build250 is not target-device tested or stable yet. |'
        break
else:
    raise SystemExit('Search module row not found')
text = '\n'.join(lines) + '\n'
text = text.replace('Search Build249, poster and Aether remain separate Active tasks', 'Search Build250, poster and Aether remain separate Active tasks')
module.write_text(text)

blocks = {
'docs/project/PROJECT_STATE.md': '''\n\n## Search Build249 nil-Type rejection → Build250 candidate — 2026-08-30\n\nBuild249 / 0.14.82 is target-device rejected for recommendation first paint while its inherited Search Dock remains accepted. Uploaded `OnePlayer-App-1788020447.log` shows `recommendation warm libraries total=21 eligible=19`; the first Movie Suggestions call returns 9 items in about 2.8 s but `accepted=0`, and the first TV call returns 9 in about 2.5 s but `accepted=0`. Exact source required returned `LibraryItem.type` to be non-nil, so Emby Suggestions responses lacking a usable `Type` were all discarded even though each request was already constrained by `IncludeItemTypes=Movie` or `Series`. This forced serial traversal through many eligible libraries and explains the endless spinner.\n\nBuild250 / 0.14.83 exact successful CI source `6e7ae960bd3cc353b8d6146aea363f3876e9e8e8` preserves CollectionType source selection and Movie/Series request filtering. If returned `Type` exists, actual Movie/Series remains mandatory; if Suggestions omits `Type`, the exact server-side `IncludeItemTypes` request is accepted as whitelist authority only when all requested types are Movie/Series. The Search view consumes this validated result without the old second `Type != nil` filter. Final run/job `33263279291 / 99128762968` passed; artifact `9717900754`; digest `sha256:f5cad646e230ffe1666e30fd2b6ce472b5d16cace168a850c9f07cf0e43e35e0`; IPA SHA-256 `f213b3d6f30ac101d563e3894c3352fdcd9c9bcb46c7a266faa48c8577e73ada`; bundle `com.embyplayerlab.app`; MinOS 15.0; IPA integrity independently verified. A prior intermediate run `33263000305` failed compilation due an accidental stale Search-view replacement and produced no candidate IPA; it is superseded and is not product evidence. Build250 evidence: **Code written ✅ / CI passed ✅ / IPA produced+verified ✅ / target-device pending / not stable**.\n''',
'docs/project/BUILD_TEST_INDEX.md': '''\n\n### Build250 / 0.14.83 — Search Suggestions nil-Type whitelist candidate\n\n- Build249 target-device: inherited Dock remains accepted, recommendation spinner remains rejected.\n- device log `OnePlayer-App-1788020447.log`: 21 total views, 19 eligible; first Movie Suggestions returned 9 but accepted 0; first TV Suggestions returned 9 but accepted 0.\n- root cause: Suggestions results on this server omit a usable decoded `Type`, while Build249's second client filter required non-nil Movie/Series and discarded server-side filtered results.\n- exact successful CI source: `6e7ae960bd3cc353b8d6146aea363f3876e9e8e8`.\n- runtime rule: eligible CollectionType + server `IncludeItemTypes` stays Movie/Series-only; actual returned Type remains authoritative when present; when absent, the exact request whitelist is trusted only if every requested type is Movie/Series. Search consumes the prevalidated output directly.\n- run/job: `33263279291 / 99128762968` — success.\n- artifact: `OnePlayer-0.14.83-Build250-Search`; ID `9717900754`; digest `sha256:f5cad646e230ffe1666e30fd2b6ce472b5d16cace168a850c9f07cf0e43e35e0`.\n- IPA SHA-256: `f213b3d6f30ac101d563e3894c3352fdcd9c9bcb46c7a266faa48c8577e73ada`.\n- package verified: `com.embyplayerlab.app`, `0.14.83 (250)`, `MinimumOSVersion=15.0`, IPA integrity passed.\n- superseded CI-only incident: run `33263000305` failed compilation before packaging after an intermediate stale Search-view replacement; no IPA from that run and it is not product evidence.\n- evidence: **Code written ✅ / CI passed ✅ / IPA produced+verified ✅ / target-device pending / not stable.**\n''',
'docs/project/TECHNICAL_DECISIONS.md': '''\n\n## Search Suggestions type authority when Emby omits `Type` — Build250 candidate\n\n- Search recommendation source eligibility remains based on real `UserViews.CollectionType`: `movies`, `tvshows`, `mixed`. Request types remain strictly Movie/Series.\n- When a Suggestions item returns a usable `Type`, that actual value remains the final whitelist authority and must be Movie or Series.\n- When the Suggestions response omits `Type`, the exact `IncludeItemTypes` request that generated that response may serve as the whitelist authority only when every requested type is itself in the Movie/Series whitelist. This is not heuristic media-type inference or a generic fallback; it trusts the server API filter that constrained the response.\n- The Search view must not reapply an incompatible `Type != nil` filter after the preloader has validated the response under this rule.\n- Build248-accepted Dock ownership/safe-area behavior remains unchanged. Build250 remains candidate-level pending target-device first-paint validation.\n'''
}
for filename, block in blocks.items():
    p = Path(filename)
    current = p.read_text()
    marker = block.strip().splitlines()[0]
    if marker not in current:
        if not current.endswith('\n'):
            current += '\n'
        p.write_text(current + block)
