name: EmbyPlayerLab

options:
  bundleIdPrefix: com.embyplayerlab
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.4"
  createIntermediateGroups: true

packages:
  KSPlayer:
    url: https://github.com/kingslay/KSPlayer.git
    exactVersion: 2.3.4

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    CLANG_ENABLE_MODULES: "YES"
    MARKETING_VERSION: "0.7.6"
    CURRENT_PROJECT_VERSION: "39"


targets:
  EmbyPlayerLab:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: KSPlayer
        product: KSPlayer
    info:
      path: Config/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.embyplayerlab.app
        MARKETING_VERSION: "0.7.6"
        CURRENT_PROJECT_VERSION: "39"
        PRODUCT_NAME: EmbyPlayerLab
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        GENERATE_INFOPLIST_FILE: "NO"
        SWIFT_OBJC_BRIDGING_HEADER: Config/EmbyPlayerLab-Bridging-Header.h
    scheme:
      testTargets: []
      gatherCoverageData: false
