name: EmbyPlayerLab

options:
  bundleIdPrefix: com.embyplayerlab
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "16.4"
  createIntermediateGroups: true

packages:
  MPVKit:
    url: https://github.com/mpvkit/MPVKit.git
    exactVersion: 1.0.0

settings:
  base:
    SWIFT_VERSION: "5.0"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    CLANG_ENABLE_MODULES: "YES"
    MARKETING_VERSION: "0.13.3"
    CURRENT_PROJECT_VERSION: "69"


targets:
  EmbyPlayerLab:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - package: MPVKit
        product: MPVKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.embyplayerlab.app
        MARKETING_VERSION: "0.13.3"
        CURRENT_PROJECT_VERSION: "69"
        PRODUCT_NAME: "OS player"
        PRODUCT_MODULE_NAME: EmbyPlayerLab
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: OSPlayerIcon
        GENERATE_INFOPLIST_FILE: "NO"
        INFOPLIST_FILE: Config/Info.plist
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: ""
        SWIFT_OBJC_BRIDGING_HEADER: Config/EmbyPlayerLab-Bridging-Header.h
    scheme:
      testTargets: []
      gatherCoverageData: false
