from pathlib import Path

p = Path("MDKLab/App/MDKKSAVIOPlayerEngine.swift")
text = p.read_text()

old_poll = '''        if ended, duration > 0, position + max(3, duration * 0.005) < duration, activeNativeSeek != nil || queuedLatestSeek != nil || pendingSeekResume != nil {\n            let recoveryTarget = latestDesiredTarget(fallback: position)\n            DiagnosticsLogger.shared.playback("MDKSeekWedge", "reason=premature-eof-during-seek position=\\(String(format: \"%.3f\", position)) duration=\\(String(format: \"%.3f\", duration)) latestTarget=\\(String(format: \"%.3f\", recoveryTarget)) action=rebuild-player-at-latest-target")\n            recoverWedgedSeek(reason: "premature-eof-during-seek", fallbackTarget: recoveryTarget, playerGeneration: generation)\n            return\n        }\n'''
new_poll = '''        if ended, duration > 0, position + max(3, duration * 0.005) < duration, activeNativeSeek != nil || queuedLatestSeek != nil || pendingSeekResume != nil {\n            let recoveryTarget = latestDesiredTarget(fallback: position)\n            activeNativeSeek = nil\n            queuedLatestSeek = nil\n            pendingSeekResume = nil\n            DiagnosticsLogger.shared.playback("MDKSeekWedge", "reason=premature-eof-during-seek position=\\(String(format: \"%.3f\", position)) duration=\\(String(format: \"%.3f\", duration)) latestTarget=\\(String(format: \"%.3f\", recoveryTarget)) action=in-place-reprepare-no-rebuild")\n            recoverStall(position: recoveryTarget, duration: duration)\n            return\n        }\n'''
if new_poll not in text:
    if old_poll not in text: raise SystemExit("pollState EOF seek anchor missing")
    text = text.replace(old_poll, new_poll, 1)

old_negative = '''                } else {\n                    let recoveryTarget = self.latestDesiredTarget(fallback: dispatchedIntent.target)\n                    DiagnosticsLogger.shared.playback("MDKSeek", "id=\\(dispatchedIntent.id) target=\\(String(format: \"%.3f\", dispatchedIntent.target)) callbackMs=\\(String(format: \"%.1f\", requestLatency)) nativeMs=\\(String(format: \"%.1f\", nativeLatency)) result=\\(actualMs) current=\\(isCurrent) action=negative-callback-recover latestTarget=\\(String(format: \"%.3f\", recoveryTarget))")\n                    self.recoverWedgedSeek(reason: "negative-callback-\\(actualMs)", fallbackTarget: recoveryTarget, playerGeneration: dispatchedIntent.playerGeneration)\n                    return\n                }\n'''
new_negative = '''                } else {\n                    let recoveryTarget = self.latestDesiredTarget(fallback: dispatchedIntent.target)\n                    let endedNow = self.hasStatus(player.mediaStatus.rawValue, bit: 6)\n                    if endedNow {\n                        self.pendingSeekResume = nil\n                        self.queuedLatestSeek = nil\n                        DiagnosticsLogger.shared.playback("MDKSeek", "id=\\(dispatchedIntent.id) target=\\(String(format: \"%.3f\", dispatchedIntent.target)) callbackMs=\\(String(format: \"%.1f\", requestLatency)) nativeMs=\\(String(format: \"%.1f\", nativeLatency)) result=\\(actualMs) current=\\(isCurrent) action=eof-negative-callback-in-place-reprepare latestTarget=\\(String(format: \"%.3f\", recoveryTarget))")\n                        self.recoverStall(position: recoveryTarget, duration: dispatchedIntent.duration)\n                        return\n                    }\n                    DiagnosticsLogger.shared.playback("MDKSeek", "id=\\(dispatchedIntent.id) target=\\(String(format: \"%.3f\", dispatchedIntent.target)) callbackMs=\\(String(format: \"%.1f\", requestLatency)) nativeMs=\\(String(format: \"%.1f\", nativeLatency)) result=\\(actualMs) current=\\(isCurrent) action=negative-callback-recover latestTarget=\\(String(format: \"%.3f\", recoveryTarget))")\n                    self.recoverWedgedSeek(reason: "negative-callback-\\(actualMs)", fallbackTarget: recoveryTarget, playerGeneration: dispatchedIntent.playerGeneration)\n                    return\n                }\n'''
if new_negative not in text:
    if old_negative not in text: raise SystemExit("negative callback anchor missing")
    text = text.replace(old_negative, new_negative, 1)

p.write_text(text)
print("Build84 MDK EOF seek rebuild escape paths closed")
