from pathlib import Path
import re

poster = Path('docs/project/current/dev/DEV-poster-grid-smoothness.md')
s = poster.read_text()
section = '''## Build229 Home-only supporting capture — 2026-08-28\n\nThe user immediately supplied a second target-device recording/log after Build229, but this capture is **Home vertical scrolling**, not the intended Library 3×3 pagination A/B. It therefore does **not** promote Build229 to target-device-tested for its Library persistence change. The intended Build229 Library test remains pending.\n\nUploaded files: `OnePlayer-App-1787907572.log` and `RPReplay_Final1787907569.mp4`. The App log contains only five `HomeCarousel settled` records and no `PosterScrollHitch`, pagination, Library snapshot read/write, or page-apply records. The 15.47 s / 30 fps recording spans approximately 08:59:13.53Z–08:59:29.00Z by filename time. Two carousel settles fall inside that span at approximately +5.214 s (`item=143014`) and +12.211 s (`item=143013`). Frame-motion inspection shows near-zero/duplicate-frame → catch-up patterns shortly after both settle points, with the cleaner second sequence around +12.30–12.37 s. Because the recording itself is only 30 fps and the App log emitted no `PosterScrollHitch`, this is **supporting correlation, not proof of a 60–70 ms app-main-thread stall**.\n\nExact Build229 source keeps the normal Home carousel timer on `.main`; `autoAdvanceCarouselIfNeeded()` starts a 0.62 s transition and schedules `settleCarousel` after 0.63 s. `settleCarousel` synchronously mutates `currentCarouselItemID`, transition IDs/progress/direction, drag state and `carouselLastSettledAt`, then logs `HomeCarousel settled`. Those state changes can invalidate Home presentation, so the approximately 7 s recurring settle cadence is a plausible contributor to a periodic “sudden twitch” subtype. However Build222 already blocked new automatic carousel transitions after Home left the top and the user still perceived Home vertical hitching, so offscreen auto-advance/settle is already rejected as the **sole or sufficient** explanation for Home vertical jitter. Do not repeat Build222 as a blind fix.\n\nCurrent interpretation: Build228's 39.7 ms synchronous Library write remains a valid contributor to the severe **Library pagination-adjacent** sample, while this new Home-only capture points to a separate periodic Home presentation/state-update correlation. The two paths must remain separate until route-specific device evidence proves otherwise.\n\n'''
anchor = '## Acceptance / protected contracts\n'
assert anchor in s
if '## Build229 Home-only supporting capture — 2026-08-28' not in s:
    s = s.replace(anchor, section + anchor, 1)
poster.write_text(s)

home = Path('docs/project/current/dev/DEV-home-carousel-drag-smoothness.md')
s = home.read_text()
section = '''## Supporting Home vertical capture on Build229 package — 2026-08-28\n\nA Build229 package recording/log was supplied while discussing poster-scroll persistence, but the visible route is Home vertical scrolling. This does not change the horizontal carousel acceptance lane. It does add one supporting runtime correlation for the separate vertical-jitter history:\n\n- `OnePlayer-App-1787907572.log` contains five `HomeCarousel settled` records only; no poster-hitch or disk-cache timing records;\n- `RPReplay_Final1787907569.mp4` is 510×1108 at 30 fps for 15.47 s; two `settled` events align by filename time at about +5.214 s and +12.211 s;\n- frame motion shortly after both events contains near-zero/duplicate-frame → catch-up signatures; the second is cleaner around +12.30–12.37 s;\n- because 30 fps recording can itself duplicate samples and there is no matching `PosterScrollHitch`, treat this as correlation only, not measured main-thread frame duration.\n\nExact Build229 Home source retains the normal main-run-loop carousel timer and `settleCarousel` mutates several Home `@State` values synchronously. A periodic settle-triggered presentation invalidation is therefore plausible for a distinct “sudden twitch” subtype. Build222 remains controlling contrary evidence: blocking new offscreen automatic transitions did **not** remove overall Home vertical hitching. Therefore no new carousel patch is justified from this correlation alone, and Build222 must not simply be repeated.\n\n'''
anchor = '## Retained interaction contract\n'
assert anchor in s
if '## Supporting Home vertical capture on Build229 package — 2026-08-28' not in s:
    s = s.replace(anchor, section + anchor, 1)
home.write_text(s)

index = Path('docs/project/BUILD_TEST_INDEX.md')
s = index.read_text()
old = re.compile(r'\| \*\*Build229 / 0\.14\.62\*\* \| Library presentation snapshot persistence off MainActor \| .*? \|')
m = old.search(s)
assert m
row = '| **Build229 / 0.14.62** | Library presentation snapshot persistence off MainActor | **CI/IPA verified; package exercised on target device on Home only; intended Library 3×3 pagination A/B still pending; not stable.** Exact source `f5e3e3eb144578c863b172e3bd3a1aa13e5c2177`; exact Build228→229 delta is five paths only. Library state snapshot capture remains MainActor-owned, while object→JSON conversion, JSON serialization and atomic disk write execute on one serial utility queue and are awaited in order. Favorites persistence/cache schema/image policy/Home owners/P0 remain unchanged. The new Home-only log contains only `HomeCarousel settled` records and no Library/pagination/snapshot timing, so it cannot validate the off-main Library persistence fix. Run/job `33156266871 / 98799654927`; artifact `9679803873`; artifact SHA-256 `8b301f7644f0dfb7e1fb80dba78069f870123c663ba5b323edc93a1e88f067b2`; IPA SHA-256 `49efcb8766cc9414a3f35e3d8fe75a04eaf6adf2ba86a40f526a5e53c40acd4c`; source ZIP SHA-256 `1de13e01617a575bf5b204e9dd546af443b8a7fdf79003e3eba1399edfb06e5a`; OnePlayer 0.14.62 (229), MinOS 15.0 independently verified. |'
s = s[:m.start()] + row + s[m.end():]
index.write_text(s)

module = Path('docs/project/MODULE_STATUS.md')
s = module.read_text()
lines = s.splitlines()
for i, line in enumerate(lines):
    if line.startswith('| Poster 3-column / poster-heavy scroll smoothness |'):
        lines[i] = '| Poster 3-column / poster-heavy scroll smoothness | **Active — Build228 device diagnostic found 39.7 ms synchronous Library snapshot persistence beside a 55.1 ms dragging hitch; Build229 off-main persistence CI/IPA verified, intended Library A/B pending** | Build228 / 0.14.61 target-device still hitches, sometimes strongly. The strongest captured grid dragging frame was 55.1 ms; latest image publish/Combine→UIKit adoption was 0.0 ms and page apply 0.3 ms, while synchronous Library snapshot persistence took 39.7 ms and ended about 8 ms before the hitch. Build229 / 0.14.62 exact source `f5e3e3eb144578c863b172e3bd3a1aa13e5c2177` moves only Library JSON conversion/serialization/atomic write to one serial utility queue. A subsequent target-device capture was Home vertical only and contained no Library/pagination/snapshot timing, so Build229 still lacks its intended Library 3×3 A/B. That Home capture has a supporting ~7 s correlation between periodic `HomeCarousel settled` events and 30 fps near-zero→catch-up samples, but Build222 already rejected offscreen auto-advance as sufficient. Favorites, Home carousel owner source and Player/Transport/Cache/Session/P0 remain unchanged; not stable. |'
    if line.startswith('| Other product modules |'):
        lines[i] = '| Other product modules | Active parallel work | Build216 / 0.14.49 remains the latest accepted overall runtime baseline. Home-carousel Build226 is materially positive and Build227 remains the horizontal CI/IPA-verified title-shimmer A/B pending target-device test. Poster-scroll Build229 is CI/IPA verified for off-main Library snapshot writing, but its intended Library 3×3 device A/B is still pending; the latest supplied capture was Home vertical only and adds a separate periodic carousel-settle correlation, not a Build229 Library verdict. |'
module.write_text('\n'.join(lines) + '\n')

state = Path('docs/project/PROJECT_STATE.md')
s = state.read_text()
s = re.sub(r'_Last updated after .*?_', '_Last updated after Build228 target-device diagnostics, Build229 off-main Library snapshot CI/IPA verification, and the subsequent Build229-package Home-only vertical capture. Build216 remains the accepted overall runtime baseline. Build229 still awaits its intended Library 3×3 pagination A/B; the Home-only capture adds a separate periodic carousel-settle correlation but does not validate the Library persistence fix._', s, count=1)
section = '''### Build229 package Home-only supporting capture\n\nThe immediate follow-up recording/log after Build229 does **not** exercise the intended Library 3×3 route. It is Home vertical scrolling, and its log contains only `HomeCarousel settled` events with no Library snapshot/pagination timing. Therefore Build229 remains target-device pending for its actual off-main persistence hypothesis.\n\nThe Home recording is 30 fps / 15.47 s. By filename timing, carousel settles land at approximately +5.214 s and +12.211 s, while frame motion shortly afterward shows near-zero/duplicate-frame → catch-up signatures. The roughly 7 s repetition matches the normal auto-advance/settle cadence in exact Build229 Home source. This is a plausible correlation for a periodic “sudden twitch” subtype, but it is not measured main-thread hitch proof because no `PosterScrollHitch` was emitted and 30 fps capture can duplicate frames. Build222 already proved that blocking new offscreen auto-advance does not remove overall Home vertical jitter, so no repeat of that patch is justified.\n\n'''
anchor = 'Work: `DEV-poster-grid-smoothness`.\n'
assert anchor in s
if '### Build229 package Home-only supporting capture' not in s:
    s = s.replace(anchor, section + anchor, 1)
state.write_text(s)
